### ISSUE TITLE
Roadmap for CTAN release

### ISSUE THREAD

**Issue by matze** [matze/mtheme#110]
This is a meta issue to discuss which features are must-haves for the CTAN release. To close this issue we need at least

- [x] identify issues that are required for 1.0, i.e. those that will break interfaces when resolved at a later time
- [x] resolve those issues

I have to agree with @benjamin-weiss that #11, #53 and #65 are not required for the CTAN release, so I will remove the milestone tags for these issues in the mean time.

Here is a comprehensive list identified by @benjamin-weiss:

### Must have

- [x] #8 Should anyway be nearly or already be done
- [x] #68 As this is just an issue we will close once version 1.0 is finished
- [x] #85 This issue or more generally spoken "an complete overhaul of the font theme" is in my opinion the major issue we should solve before releasing on CTAN
- [x] #95 This is actually linked to #85 and should be solved with it together. The title graphics changes discussed in it are strictly speaking no must have feature for version 1.0, but as I want to get started on that anyway soon
- [x] #99 there is a PR for it at #115
- [x] #112 Changing the name

### Optional / Later

- #11 As already agreed
- #29 Although it is an really important problem
- #46 Also just an additional feature, as pgfkeys options are now implemented I don't see where this could break backwards compatibility
- #53 As already agreed
- #65 As already agreed
- #87 This is just an annoyance where I do not see a solution at this point.
- #97 
- #108 For version 1.0 I would just add an information, that the theme is available on CTAN and can be installed via the users package manager. If someone provides an installation guide for Windows, ok. We will obviously integrate it.
- #109

### Unclear

- #69 Here I'm a bit unsure. Is the system in place already good enough, that we can keep it that way and close the issue? Or do we want to make changes here that will break backwards compatibility?

**Comment by benjamin-weiss** [comment]
Alright. So after the quick look yesterday now my in detail opinion on the matter. The sooner we release to CTAN the better. So in the following list I limited the number of issues as far as possible.

#8 Should anyway be nearly or already be done → **close? or keep for version 1.0**
#11 As already agreed → not a must have feature
#29 Although it is an really important problem → no a must have feature
#46 Also just an additional feature, as pgfkeys options are now implemented I don't see where this could break backwards compatibility → not a must have feature 
#53 As already agreed → not a must have feature
#65 As already agreed → not a must have feature
#68 As this is just an issue we will close once version 1.0 is finished → **keep for version 1.0**
#69 Here I'm a bit unsure. Is the system in place already good enough, that we can keep it that way and close the issue? Or do we want to make changes here that will break backwards compatibility?
#85 This issue or more generally spoken "an complete overhaul of the font theme" is in my opinion the major issue we should solve before releasing on CTAN → **keep for version 1.0**
#87 This is just an annoyance where I do not see a solution at this point. → not a must have feature
#95 This is actually linked to #85 and should be solved with it together. The title graphics changes discussed in it are strictly speaking no must have feature for version 1.0, but as I want to get started on that anyway soon → **keep for version 1.0 ?**
#97 → not a must have feature
#99 It would be really nice if this would be fixed in version 1.0, but I'm still unsure about the best way to fix it. So → not a must have feature
#108 For version 1.0 I would just add an information, that the theme is available on CTAN and can be installed via the users package manager. If someone provides an installation guide for Windows, ok. We will obviously integrate it. But it is → not a must have feature.
#109 → not a must have feature.

**Comment by rchurchley** [comment]
I agree with the issues you've identified as necessary. I would also submit #112 — changing the name of the packages will be the biggest breaking change of all, and should be completed before the 1.0.0 release.

**Comment by benjamin-weiss** [comment]
I think nearly all "must have" issues are closed now. So we can probably make a 1.0.0 CTAN release very soon. Someone should check if the name change is completely done (but I think @rchurchley already did a good job on that) and we should probably finish the discussion in #138 about renaming the `titleformat` options. Because this would also break backwards compatibility if we decide to change this at a later point. But other than that I think we are good to go. Do you guys agree?

**Comment by matze** [comment]
> Someone should check if the name change is completely done

I have replaced some more occurences of mtheme but I am still hesitating to push the change because I also changed the package name from *m* to *metropolis*. This will break any existing information about this theme in the wild. Should we do the final change?

**Comment by benjamin-weiss** [comment]
Sure it is a nuisance. But we knew that we would be in this situation at some point when we decided to rename it. So I think you should just merge it. But you could maybe add an eye-catching notice about the renaming to the `README.md`.

**Comment by matze** [comment]
Pushed the name change and modification of the `README.md`.

**Comment by benjamin-weiss** [comment]
@matze I think there are some small changes left.

* uncomment my paragraph about installing from CTAN in the documentation
* set version number in documentation
* I haven't really looked at your changes to the makefile, but according to CTAN all the files in the tarball should be in a folder called metropolis
* change the date in `ProvidesPackage`of the source files to the release date
* add the `demo.pdf` to the tarball

After the CTAN release (as I already proposed in #156) I think we should remove the PDFs completely from the repository and link to the PDFs hosted by CTAN and introduce a developer branch.

**Comment by matze** [comment]
> I haven't really looked at your changes to the makefile, but according to CTAN all the files in the tarball should be in a folder called metropolis.

Well my change actually did that, except for calling the folder `mtheme` :rage4: 

I will care for these points once I merged #161.

**Comment by matze** [comment]
So, the tarball is in the queue, I'll remove the PDFs and update the reference once it's finally landed.
